### ISSUE TITLE
Support for GNN as underlying model?

### ISSUE THREAD

**Issue by venomouscyanide** [Graph-COM/SUREL#2]
Hi,

I was trying to run the SUREL algorithm with a GNN `Net` model. However, I could not see any GNN model architecture being supported in `models.py`/`layers.py` file. Could you please let me know if there is currently support for using a GNN model as the underlying training `Net`?

Thanks in advance,
Paul

**Comment by VeritasYin** [comment]
Hello Paul,

Thank you for your interest in our work. SUREL employs RNN to encode sampled random walks pairing with relative positional encoding as the subgraph representation. We currently do not provide the support for GNN models. But it can certainly integrate GNNs as underlying backbones. I will let you know for further update. And please feel free to contribute if you're interested!

Best,
Haoteng

**Comment by venomouscyanide** [comment]
Hi Haoteng,

Thank you for the quick response. I was wondering how the walk data paired with RPE information(the query level RPE), which is sequential data, can be fed to a canonical GNN architecture(such as GCN)? I understand it makes sense to use with LSTMs, RNNs etc. However, I am having difficulty picturing how a GNN can be used.

Forgive me if the question is dumb.

-Paul

**Comment by VeritasYin** [comment]
The collected walks essentially can be regarded as downsampled subgraphs, which can be directly fed into GCN for representation learning, where RPEs can be used as node features.

**Comment by venomouscyanide** [comment]
Hi Haoteng,

Thank you so much for the detailed response. That makes sense. I'll try this out. Looking forward to seeing SUREL in VLDB '22 and other future works!

Closing this issue as it has been addressed.
