### ISSUE TITLE
Support for custom datasets ?

### ISSUE THREAD

**Issue by shhs29** [Graph-COM/SUREL#3]
Hi,

I was wondering if SUREL currently supports testing with custom datasets such as Planetoid or attributed datasets.

Thanks and Regards,
Shweta Ann Jacob

**Comment by VeritasYin** [comment]
Hello Shweta,

SUREL directly supports datasets with the format of OGB. You might try to customize class DEDataset() in dataloaders.py. As for attributed dataset, we provide the basic support. Later, I will push an update for better support.

Best, Haoteng

**Comment by shhs29** [comment]
Hi Haoteng,

Thanks a lot for your reply! I will try incorporating the custom datasets and looking forward to the new updates.

Thanks and Regards,
Shweta Ann Jacob
