### ISSUE TITLE
Error: undefined symbol PyArray_XDECREF_ERR

### ISSUE THREAD

**Issue by emalgorithm** [Graph-COM/SUREL#6]
Hi,

I am not able to run the model as I encounter some errors.

First, when running `cd surel_gacc;python3 setup.py install`, I get the following warnings:
> graph_acc.c: In function ‘np_sample’:
> graph_acc.c:344:5: warning: implicit declaration of function ‘PyArray_XDECREF_ERR’; did you mean ‘PyArray_XDECREF’? [-Wimplicit-function-declaration]
>      PyArray_XDECREF_ERR(oarr);
>      ^~~~~~~~~~~~~~~~~~~
>      PyArray_XDECREF
> At top level:
> graph_acc.c:92:13: warning: ‘f_format’ defined but not used [-Wunused-function]
>  static void f_format(const npy_intp *dims, int *CArrays) {
>              ^~~~~~~~
> 

Then, running the model fails with:

> (surel) erossi@erossi-research-vm:~/SUREL$ python main.py --dataset ogbl-citation2 --metric mrr --num_step 4 --num_walk 100
> Traceback (most recent call last):
>   File "/home/erossi/SUREL/main.py", line 7, in <module>
>     from surel_gacc import run_sample
> ImportError: /opt/conda/envs/surel/lib/python3.9/site-packages/SUREL_GAcc-1.0-py3.9-linux-x86_64.egg/surel_gacc.cpython-39-x86_64-linux-gnu.so: undefined symbol: PyArray_XDECREF_ERR

Any advice on what I may be missing?

**Comment by VeritasYin** [comment]
Hi, thanks for reporting this issue.

Could you check the version of Numpy installed in your environment? ‘PyArray_XDECREF_ERR’ may not be supported in later version of Numpy (<=1.19.2).

**Comment by emalgorithm** [comment]
Thanks! That fixes it.

However, I'm now encountering a CUDA memory error when using a machine with a K80 GPU with 12GB of memory:

```

> `INFO:root:Samples: valid 6008 by 10000 test 46329 by 100000 metric: Hits@50
> INFO:root:Running Round 1
> Traceback (most recent call last):
>   File "main.py", line 187, in <module>
>     loss, auc = train(model, optimizer, data, gT)
>   File "/home/ubuntu/projects/SUREL/train.py", line 21, in train
>     pred = model(Tf, [wl, wr])
>   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/ubuntu/projects/SUREL/models/model.py", line 90, in forward
>     out_i, out_j = self.rnn(x[0], self.walks), self.rnn(x[1], self.walks)
>   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/ubuntu/projects/SUREL/models/layer.py", line 82, in forward
>     out, _ = self.rnn(x)
>   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 582, in forward
>     self.dropout, self.training, self.bidirectional, self.batch_first)
> RuntimeError: CUDA out of memory. Tried to allocate 3.43 GiB (GPU 0; 11.17 GiB total capacity; 8.34 GiB already allocated; 2.31 GiB free; 8.51 GiB reserved in total by PyTorch)`

```

Any idea how to solve this?

**Comment by VeritasYin** [comment]
For the CUDA OOM error, you might need to reduce the batch size, the number of negative sampling k or adjust num_walks / num_steps to make it feasible. Our experiments were performed on RTX 6000 with 24GB of memory. The parameters used can be found in Appendix D.3.
