### ISSUE TITLE
Question about epoch and batch_size

### ISSUE THREAD

**Issue by baoleai** [Graph-COM/SUREL#9]
Hi, what is `B_size` in main.py, does it mean training batch_size?  How can I get an epoch time(an epoch means all training edges have been traversed). Can I get it from `num_train_edges / B_size * time_of_a_B_size` ?

**Comment by VeritasYin** [comment]
Hi, `B_size` is the batch capacity of seed nodes, which is not the training `batch_size`. The algorithm design of SUREL doesn't require to traverse all training edges (at most 5%). Each time, it randomly chooses a seed-set of nodes V from the union of queries Q (links); and then runs breath-first search to expand V and Q until |V| = `B_size` or |Q| = `batch_size`. Here, we also pair each positive edge with `k`-many negative edges in the same batch.

The full training pipeline of SUREL is summarized in Algorithm 2 of [our paper](https://arxiv.org/pdf/2202.13538.pdf).
